welcome:
  Welcome to School Management Database System !!
spring:
  datasource:   
    url: "jdbc:mysql://localhost:3306/schooldb"
    username: root
    password: Cena0607.
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update     
    show-sql: true    
logging:
  level:
    org:
      hibernate:
        type: debug    
server:
  port: '8082'
